### ISSUE TITLE
请问能在我项目中引用您的项目吗

### ISSUE THREAD

**Issue by zlx362211854** [ch957869975/md-editor#1]
之前我在我的  https://github.com/zlx362211854/DES    项目中使用了stackedit，这是一款开源的线上版本的编辑器，在网络不好的情况下会有卡顿，看到您的项目，我想引入我的离线版本，请问可以吗？

**Comment by ch957869975** [comment]
我的这个是一个单独的vue小项目，不太清楚你是否能够较为方便的引用到自己项目中，后续我会整理成一个npm包，还请您关注

**Comment by ch957869975** [comment]
@zlx362211854

**Comment by zlx362211854** [comment]
> 我的这个是一个单独的vue小项目，不太清楚你是否能够较为方便的引用到自己项目中，后续我会整理成一个npm包，还请您关注

现在的版本就能使用了，打包后部署成静态服务就行

**Comment by ch957869975** [comment]
> > 我的这个是一个单独的vue小项目，不太清楚你是否能够较为方便的引用到自己项目中，后续我会整理成一个npm包，还请您关注
> 
> 现在的版本就能使用了，打包后部署成静态服务就行

如果是这样的话，欢迎使用。(如果可以的话，请添加一个原址链接😊）

**Comment by zlx362211854** [comment]
> > > 我的这个是一个单独的vue小项目，不太清楚你是否能够较为方便的引用到自己项目中，后续我会整理成一个npm包，还请您关注
> > 
> > 
> > 现在的版本就能使用了，打包后部署成静态服务就行
> 
> 如果是这样的话，欢迎使用。(如果可以的话，请添加一个原址链接😊）

好的，谢谢😄
